### ISSUE TITLE
Code does not compile with Xcode 6.4, Mac OS X SDK 10.10

### ISSUE THREAD

**Issue by bunkersmith** [mdejong/MvidMovieMaker#2]
Errors in main.m:

/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1005:39: Unknown type name 'Media'
/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1006:39: Unknown type name 'Track'
/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1027:25: Use of undeclared identifier 'nextTimeStep'
/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1232:3: Use of undeclared identifier 'Media'
/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1233:10: Use of undeclared identifier 'firstTrackQuicktimeMedia'
/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1246:31: Use of undeclared identifier 'firstTrackQuicktimeMedia'
/Users/carlsmith/Documents/SoftwareLibraries/MvidMovieMaker-master/main.m:1339:62: Use of undeclared identifier 'firstTrackQuicktimeMedia'

Also, 81 warnings in various files

**Comment by bunkersmith** [comment]
These errors were caused by incorrect GitHub usage on my part - sorry!
